apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config-yml
  namespace: default
  labels:
    role: logstash
    service: logging
data:
  # Configuration files: server, input, filters and output
  # ======================================================
  logstash.yml: |
    http.host: "0.0.0.0"
    xpack.monitoring.elasticsearch.hosts: [ "http://elasticsearch:9200" ]

    ## X-Pack security credentials
    #
    xpack.monitoring.enabled: true
    xpack.monitoring.elasticsearch.username: elastic
    xpack.monitoring.elasticsearch.password: changeme
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config-conf
  namespace: default
  labels:
    role: logstash
    service: logging
data:
  logstash.conf: |
    input {
    	beats {
    		port => 5044
    	}

    	tcp {
    		port => 5000
    	}
    }

    ## Add your filters / logstash plugins configuration here

    output {
    	elasticsearch {
    		hosts => "elasticsearch:9200"
    		user => "elastic"
    		password => "changeme"
    		ecs_compatibility => disabled
    	}
    }
