apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
  namespace: default
  labels:
    role: kibana
data:
  # Configuration files: server, input, filters and output
  # ======================================================
  kibana.yml: |
    server.name: kibana
    server.host: 0.0.0.0
    elasticsearch.hosts: [ "http://elasticsearch:9200" ]
    monitoring.ui.container.elasticsearch.enabled: true

    ## X-Pack security credentials
    #
    elasticsearch.username: elastic
    elasticsearch.password: changeme
