apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
  namespace: default
  labels:
    role: elasticsearch
data:
  # Configuration files: server, input, filters and output
  # ======================================================
  elasticsearch.yml: |
    cluster.name: "docker-cluster"
    network.host: 0.0.0.0

    ## X-Pack settings
    ## see https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-xpack.html
    #
    xpack.license.self_generated.type: basic
    xpack.security.enabled: true
    xpack.monitoring.collection.enabled: true